version: '3.8'

services:
  myst-node:
    build: .
    container_name: myst-node
    environment:
      - MYST_KEY=${MYST_KEY}
    restart: unless-stopped
    privileged: true
    volumes:
      - myst_data:/root/.mysteriumium
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  myst_data: